---
- hosts: store.atvpc.com
  tasks:
    - name: Install webstore base packages
      become: true
      become_method: sudo
      apt: name={{ item }} state=present
      with_items:
        - apache2
        - python-certbot-apache
        - composer
        - mariadb-client
        - mariadb-server
        - redis-server
        - software-properties-common
        - sendmail
    - name: Add php7.1 third-party repo
      become: true
      become_method: sudo
      command: add-apt-repository ppa:ondrej/php
    - name: Add php7.1 packages
      become: true
      become_method: sudo
      update_cache: yes
      apt: name={{ item }} state=present
      with_items:
        - libapache2-mod-php7.1
        - php7.1-bcmath
        - php7.1-mcrypt
        - php7.1-curl
        - php7.1-cli
        - php7.1-mysql
        - php7.1-gd
        - php7.1-xsl
        - php7.1-json
        - php7.1-intl
        - php-pear
        - php7.1-dev
        - php7.1-common
        - php7.1-mbstring
        - php7.1-zip
        - php7.1-soap
        - php7.1-xml
    - name: Clone git config repo
      git:
        repo: 'https://github.com/atvpc/conf.git'
        dest: /srv/conf
    - name: Stow config
      become: true
      become_method: sudo
      command: stow -t / store.atvpc.com
      args:
        chdir: /srv/conf
    - name: Fix htdocs permissions from stow
      become: true
      become_method: sudo
      file:
        dest: /srv/htdocs/store.atvpc.com
        owner: www-data
        group: www-data
        mode: u=rwX,g=rwX,o=rX
    - name: Enable services
      become: true
      become_method: sudo
      systemd: name={{ item }} enabled=yes state=started
      with_items:
        - apache2
        - mariadb
        - redis-server
    - name: Allow Apache thru firewall
      become: true
      become_method: sudo
      command: ufw allow "Apache Full"
