---
- hosts: www.atvpc.com
  tasks:
    - name: Install webserver packages
      become: true
      become_method: sudo
      apt: name={{ item }} state=present
      with_items:
        - certbot
        - nginx
        - php-fpm
        - php7.2-mbstring
        - php7.2-xml
        - python-certbot-nginx
    - name: Clone git config repo
      git:
        repo: 'https://github.com/atvpc/conf.git'
        dest: /srv/conf
    - name: Stow config
      become: true
      become_method: sudo
      command: stow -t / www.atvpc.com
      args:
        chdir: /srv/conf
    - name: Enable services
      become: true
      become_method: sudo
      systemd: name={{ item }} enabled=yes state=started
      with_items:
        - php7.2-fpm
        - nginx
    - name: Allow nginx thru firewall
      become: true
      become_method: sudo
      command: ufw allow "Nginx Full"

# Use LetsEncrypt for HTTPS (TODO: automate w/o prompts)
# sudo certbot --nginx -d atvpc.com -d www.atvpc.com -d wiki.atvpc.com
# sudo systemctl restart nginx
#
# Maintains secrets outside of VCS (TODO: figure out how to securely automate distribution)
# cd /srv/secrets; sudo stow -t / www.atvpc.com
